services:
  - type: web
    name: figma-to-code-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://figma-to-code-pi.vercel.app
      - key: FIGMA_CLIENT_ID
        sync: false
      - key: FIGMA_CLIENT_SECRET
        sync: false 